/**
 * Auto-naming for recording sessions.
 *
 * A session starts life as `Recording <date> <time>` and is renamed once
 * analysis returns a `title` — a short, content-derived topic — which we
 * stamp with the recording's date and time:  `Trinergy PD Correction_25 Aug 3:30 PM`
 *
 * Renaming ONLY ever applies to a title still in the untouched fallback form.
 * Sessions the user named, and sessions recorded before this existed, are
 * never rewritten.
 */
import { formatTitleStamp } from './formatters';

/** Longest topic we keep before the date stamp — the sidebar truncates past this anyway. */
const MAX_TOPIC_LENGTH = 60;

/**
 * Topics that name a category rather than a subject. A session called
 * "Planning_25 Aug 3:30 PM" tells the user nothing the fallback didn't, so we
 * keep the fallback instead. Includes every `meetingType` enum value, since
 * the likeliest model failure is echoing that field into `title`.
 */
const UNINFORMATIVE_TOPICS = new Set([
  'standup', 'planning', 'brainstorm', 'review', 'retro', 'retrospective',
  '1on1', '1:1', 'one on one', 'all-hands', 'all hands', 'other',
  'meeting', 'recording', 'untitled', 'conversation', 'discussion',
  'session', 'sync', 'call', 'catch-up', 'catch up', 'update', 'updates',
  'notes', 'test', 'audio', 'transcript', 'n/a', 'na', 'none', 'unknown',
]);

/**
 * True only for the `Recording <date> <time>` string the app generates itself.
 * Anything the user typed (or an imported/manual-entry title) fails this and
 * is left alone.
 */
export const isAutoGeneratedTitle = (title: string): boolean =>
  /^Recording \d/.test(title.trim());

/**
 * Clean a model-supplied topic into something safe to show as a title.
 * Returns '' when the model gave us nothing usable, which means "keep the
 * fallback name".
 */
export const sanitizeTopic = (raw: string | undefined): string => {
  if (!raw) return '';
  let topic = raw
    .replace(/\s+/g, ' ')                       // collapse newlines/tabs the model may emit
    .replace(/^["'`\s]+|["'`\s]+$/g, '')        // strip wrapping quotes
    .replace(/[_\-–—:,.\s]+$/, '')              // strip trailing separators/punctuation
    .trim();

  // The model is told not to include a date, but strip one if it slips in so
  // we don't end up with the date twice.
  topic = topic.replace(/[_\-–—\s]+\d{1,2}(st|nd|rd|th)?[\s/-]\w+([\s/-]\d{2,4})?$/i, '').trim();

  // A model that ignored the instructions and echoed the fallback, or returned
  // a bare category, is no better than the name we already have.
  if (!topic || isAutoGeneratedTitle(topic)) return '';
  if (UNINFORMATIVE_TOPICS.has(topic.toLowerCase())) return '';

  if (topic.length > MAX_TOPIC_LENGTH) {
    // Cut on a word boundary rather than mid-word.
    const cut = topic.slice(0, MAX_TOPIC_LENGTH);
    const lastSpace = cut.lastIndexOf(' ');
    topic = (lastSpace > 30 ? cut.slice(0, lastSpace) : cut).replace(/[_\-–—:,.\s]+$/, '');
  }

  return topic;
};

/**
 * Compose the final session title, or return null to keep the existing one.
 *
 * @param currentTitle  the session's title right now
 * @param topic         `analysis.title` as returned by the model
 * @param date          the recording's start timestamp
 */
export const buildSessionTitle = (
  currentTitle: string,
  topic: string | undefined,
  date: number,
): string | null => {
  if (!isAutoGeneratedTitle(currentTitle)) return null; // user-named or pre-existing — hands off
  const clean = sanitizeTopic(topic);
  if (!clean) return null;                              // nothing better to offer
  return `${clean}_${formatTitleStamp(date)}`;
};
